
# Copyright 2025 NXP
#
# SPDX-License-Identifier: Apache-2.0
CONFIG_MCUX_PRJSEG_module.board.lvgl=y
CONFIG_LV_CONF_SKIP=n
CONFIG_LV_FONT_MONTSERRAT_16=y
CONFIG_LV_FONT_MONTSERRAT_24=y
CONFIG_LV_USE_SYSMON=y
CONFIG_LV_USE_OBSERVER=y
CONFIG_LV_USE_PERF_MONITOR=y
CONFIG_LV_USE_VGLITE_ASSERT=n
CONFIG_LV_USE_ASSERT_NULL=n
CONFIG_LV_USE_ASSERT_MALLOC=n
CONFIG_LV_USE_LOG=y
CONFIG_LV_LOG_LEVEL_ERROR=y
CONFIG_LV_CONF_MINIMAL=y
CONFIG_LV_USE_LABEL=y
CONFIG_LV_USE_THEME_DEFAULT=y

CONFIG_MCUX_COMPONENT_CMSIS_Driver_Include.SPI=y
CONFIG_MCUX_COMPONENT_CMSIS_Driver_Include.I2C=y

CONFIG_MCUX_COMPONENT_component.gpio_adapter=y

CONFIG_MCUX_COMPONENT_driver.cmsis_lpspi=y
CONFIG_MCUX_COMPONENT_driver.cmsis_lpi2c=y

CONFIG_MCUX_PRJSEG_module.board.lvgl=n


